

GET http://localhost:3001/api/item


###
POST http://localhost:3001/api/item
###
PUT http://localhost:3001/api/item/64ba5bf10b864c2cd7021887
Content-Type: application/json

{   
    "code": "v3",
    "price": "2 tỷ - 3 tỷ",
    "amenities": null,
    "rooms": null
}
###
GET http://localhost:3001/api/item/64b9f30683c26d331d90aab8
Content-Type: application/json

###
DELETE http://localhost:3001/api/item/64ba5bf10b864c2cd7021887

###
POST  http://localhost:3001/api/user/register
Content-Type: application/json

{
    "fullName": "nguyenkhacduy",
    "phoneNumber": "0778125400",
    "password": "12345"
}
###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "phoneNumber": "0778125400",
    "password": "12345"
}

###
POST http://localhost:3001/api/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGM1Y2Y4MjBlMzgyYzA2MTEwMzZiYmYiLCJpYXQiOjE2OTA4NTgyMTMsImV4cCI6MTY5MTQ2MzAxM30.1MH7kTsq_Qy2IqR-cgHUIiswpv4oYWZBvOKJK2dEtck"
}

###
GET http://localhost:3001/api/user/getlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOnsidXNlcklEIjoiNjRjNWNmODIwZTM4MmMwNjExMDM2YmJmIiwiaWF0IjoxNjkwODU4MjEzLCJleHAiOjE2OTE0NjMwMTN9LCJpYXQiOjE2OTA4NTg0NDksImV4cCI6MTY5MDg1ODUwOX0.gg7XSOorWvB4008ErXj3P5eREJlYws5e84j0NXiMMTU

###
DELETE http://localhost:3001/api/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGM1Y2Y4MjBlMzgyYzA2MTEwMzZiYmYiLCJpYXQiOjE2OTA4NTkzODcsImV4cCI6MTY5MTQ2NDE4N30.5WtFLC-Q9FbLrqrcy3V1oAwaSZDJk52TxpYhjavoC2Q"
}
